#!/bin/bash

# Generate ICC Key and Certificate for Colossus Network
# Creates card (ICC) keys and signs certificate with Issuer key
#
# Usage:
#   ./generate-icc-cert.sh [issuer_private_key] [pan] [output_dir]
#
# Arguments:
#   issuer_private_key - Path to Issuer private key PEM file
#   pan                - Card PAN (16 digits, default: auto-generate with Colossus BIN)
#   output_dir         - Output directory for ICC keys (default: ./keys/icc)
#
# Examples:
#   ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem
#   ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem 6767676712345674
#   ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem 6767676712345674 ./card_keys
#
# Outputs:
#   - icc_private.pem      - ICC private key (KEEP ON CARD ONLY!)
#   - icc_public.pem       - ICC public key
#   - icc_modulus.bin      - Raw modulus (256 bytes)
#   - icc_exponent.bin     - Raw exponent
#   - icc_certificate.bin  - Signed ICC certificate (256 bytes)
#   - icc_remainder.bin    - Certificate remainder (if needed)
#   - icc_info.txt         - Key and certificate details
#   - icc_config.yaml      - YAML configuration for card personalization

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${CYAN}$1${NC}"
}

print_step() {
    echo -e "${MAGENTA}[STEP]${NC} $1"
}

# Luhn checksum verification
verify_luhn() {
    local number="$1"
    local sum=0
    local length=${#number}
    
    for ((i=length-1; i>=0; i--)); do
        digit=${number:$i:1}
        position=$(( (length - 1 - i) % 2 ))
        
        if [ $position -eq 1 ]; then
            digit=$(( digit * 2 ))
            if [ $digit -gt 9 ]; then
                digit=$(( digit - 9 ))
            fi
        fi
        
        sum=$(( sum + digit ))
    done
    
    [ $(( sum % 10 )) -eq 0 ]
}

# Generate random PAN with Colossus BIN
generate_pan() {
    local bin="67676767"
    local account=$(printf "%07d" $(( RANDOM * RANDOM % 10000000 )))
    local base="${bin}${account}"
    
    # Calculate Luhn checksum
    local sum=0
    local length=${#base}
    
    for ((i=length-1; i>=0; i--)); do
        digit=${base:$i:1}
        position=$(( (length - 1 - i) % 2 ))
        
        if [ $position -eq 0 ]; then
            digit=$(( digit * 2 ))
            if [ $digit -gt 9 ]; then
                digit=$(( digit - 9 ))
            fi
        fi
        
        sum=$(( sum + digit ))
    done
    
    checksum=$(( (10 - (sum % 10)) % 10 ))
    echo "${base}${checksum}"
}

# Show help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Generate ICC Key and Certificate for Colossus Network"
    echo ""
    echo "Usage:"
    echo "  ./generate-icc-cert.sh [issuer_private_key] [pan] [output_dir]"
    echo ""
    echo "Arguments:"
    echo "  issuer_private_key - Path to Issuer private key PEM file"
    echo "  pan                - Card PAN (16 digits, default: auto-generate)"
    echo "  output_dir         - Output directory (default: ./keys/icc)"
    echo ""
    echo "Examples:"
    echo "  ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem"
    echo "  ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem 6767676712345674"
    echo "  ./generate-icc-cert.sh ./keys/issuer/issuer_private.pem 6767676712345674 ./card_keys"
    echo ""
    echo "Output Files:"
    echo "  icc_private.pem      - ICC private key (KEEP ON CARD!)"
    echo "  icc_public.pem       - ICC public key"
    echo "  icc_modulus.bin      - Raw 256-byte modulus"
    echo "  icc_exponent.bin     - Raw exponent"
    echo "  icc_certificate.bin  - Signed certificate (256 bytes)"
    echo "  icc_remainder.bin    - Certificate remainder"
    echo "  icc_info.txt         - Detailed information"
    echo "  icc_config.yaml      - Card setup configuration"
    echo ""
    echo "Prerequisites:"
    echo "  - Issuer private key (generated by ./generate-issuer-cert.sh)"
    echo "  - OpenSSL installed"
    echo ""
    exit 0
fi

# Parse arguments
ISSUER_PRIVATE_KEY="${1:-./keys/issuer/issuer_private.pem}"
CARD_PAN="${2:-}"
OUTPUT_DIR="${3:-./keys/icc}"

# Validate Issuer private key exists
if [ ! -f "$ISSUER_PRIVATE_KEY" ]; then
    print_error "Issuer private key not found: $ISSUER_PRIVATE_KEY"
    echo ""
    print_info "Generate Issuer key and certificate first:"
    echo "  ./generate-issuer-cert.sh ./keys/capk/capk_private.pem"
    echo ""
    exit 1
fi

# Generate or validate PAN
if [ -z "$CARD_PAN" ]; then
    CARD_PAN=$(generate_pan)
    print_info "Auto-generated PAN: $CARD_PAN"
else
    # Validate PAN format
    if ! [[ "$CARD_PAN" =~ ^[0-9]{8,19}$ ]]; then
        print_error "Invalid PAN format: $CARD_PAN"
        print_info "PAN must be 8-19 digits"
        exit 1
    fi
    
    # Verify Luhn checksum
    if ! verify_luhn "$CARD_PAN"; then
        print_warning "PAN failed Luhn checksum validation: $CARD_PAN"
        print_warning "Continuing anyway..."
    fi
fi

# Configuration
KEY_SIZE=2048
EXPONENT=3  # Standard EMV exponent
COLOSSUS_BIN="67676767"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
CERT_SERIAL=$(printf "%08X" $RANDOM$RANDOM)
EXPIRY_DATE="251231"  # YYMMDD format (Dec 31, 2025)

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Show banner
echo ""
print_header "═══════════════════════════════════════════════════════════"
print_header "  Colossus ICC Certificate Generator (RSA-2048)"
print_header "═══════════════════════════════════════════════════════════"
echo ""

print_info "Configuration:"
echo "  Issuer Key:     $ISSUER_PRIVATE_KEY"
echo "  Card PAN:       $CARD_PAN"
echo "  Key Size:       RSA-$KEY_SIZE"
echo "  Public Exp:     $EXPONENT (0x$(printf '%02X' $EXPONENT))"
echo "  Colossus BIN:   $COLOSSUS_BIN"
echo "  Cert Serial:    $CERT_SERIAL"
echo "  Expiry Date:    $EXPIRY_DATE"
echo "  Output Dir:     $OUTPUT_DIR"
echo ""

# Check for OpenSSL
if ! command -v openssl &> /dev/null; then
    print_error "OpenSSL not found. Please install OpenSSL."
    exit 1
fi

# Define output files
ICC_PRIVATE_KEY="$OUTPUT_DIR/icc_private.pem"
ICC_PUBLIC_KEY="$OUTPUT_DIR/icc_public.pem"
ICC_MODULUS="$OUTPUT_DIR/icc_modulus.bin"
ICC_EXPONENT="$OUTPUT_DIR/icc_exponent.bin"
ICC_CERT="$OUTPUT_DIR/icc_certificate.bin"
ICC_REMAINDER="$OUTPUT_DIR/icc_remainder.bin"
INFO_FILE="$OUTPUT_DIR/icc_info.txt"
CONFIG_FILE="$OUTPUT_DIR/icc_config.yaml"

# Step 1: Generate ICC RSA-2048 key pair
print_step "1/6 Generating ICC RSA-2048 key pair..."
openssl genrsa -out "$ICC_PRIVATE_KEY" -3 $KEY_SIZE 2>&1 | grep -v "^[.+]" || true
print_success "ICC private key generated"

# Step 2: Extract public key
print_step "2/6 Extracting ICC public key..."
openssl rsa -in "$ICC_PRIVATE_KEY" -pubout -out "$ICC_PUBLIC_KEY" 2>/dev/null
print_success "ICC public key extracted"

# Step 3: Extract modulus and exponent
print_step "3/6 Extracting modulus and exponent..."
openssl rsa -in "$ICC_PRIVATE_KEY" -noout -modulus 2>/dev/null | \
    sed 's/Modulus=//' | \
    xxd -r -p > "$ICC_MODULUS"

ICC_MODULUS_SIZE=$(stat -f%z "$ICC_MODULUS" 2>/dev/null || stat -c%s "$ICC_MODULUS" 2>/dev/null)
print_success "Modulus extracted: $ICC_MODULUS_SIZE bytes"

ICC_EXPONENT_HEX=$(openssl rsa -in "$ICC_PRIVATE_KEY" -noout -text 2>/dev/null | \
    grep "publicExponent:" | \
    sed 's/.*0x//' | \
    sed 's/).*//')

# Ensure even number of hex digits
if [ $(( ${#ICC_EXPONENT_HEX} % 2 )) -ne 0 ]; then
    ICC_EXPONENT_HEX="0$ICC_EXPONENT_HEX"
fi

echo -n "$ICC_EXPONENT_HEX" | xxd -r -p > "$ICC_EXPONENT"
ICC_EXPONENT_DEC=$((16#$ICC_EXPONENT_HEX))
print_success "Exponent extracted: $ICC_EXPONENT_DEC (0x$ICC_EXPONENT_HEX)"

# Step 4: Get Issuer modulus size for certificate size
print_step "4/6 Analyzing Issuer key for certificate size..."
ISSUER_MODULUS_SIZE=$(openssl rsa -in "$ISSUER_PRIVATE_KEY" -noout -modulus 2>/dev/null | \
    sed 's/Modulus=//' | wc -c)
ISSUER_MODULUS_SIZE=$(( ($ISSUER_MODULUS_SIZE - 1) / 2 ))
print_info "Issuer modulus size: $ISSUER_MODULUS_SIZE bytes"
print_info "Certificate size will be: $ISSUER_MODULUS_SIZE bytes"

CERT_SIZE=$ISSUER_MODULUS_SIZE

# EMV ICC Public Key Certificate structure
# Similar to Issuer cert but with different fields
METADATA_SIZE=21  # ICC certs have more metadata
HASH_AND_TRAILER=33
KEY_SPACE=$(( CERT_SIZE - METADATA_SIZE - HASH_AND_TRAILER ))

# Step 5: Build EMV ICC Certificate
print_step "5/6 Building EMV ICC Certificate structure..."

print_info "Certificate structure:"
echo "  Total size:     $CERT_SIZE bytes"
echo "  Metadata:       $METADATA_SIZE bytes"
echo "  Key space:      $KEY_SPACE bytes"
echo "  Hash+Trailer:   $HASH_AND_TRAILER bytes"
echo "  ICC key:        $ICC_MODULUS_SIZE bytes"

# Determine if we need remainder
if [ $ICC_MODULUS_SIZE -gt $KEY_SPACE ]; then
    REMAINDER_SIZE=$(( ICC_MODULUS_SIZE - KEY_SPACE ))
    print_info "ICC key requires REMAINDER: $REMAINDER_SIZE bytes"
    
    # Extract leftmost part for certificate
    dd if="$ICC_MODULUS" bs=1 count=$KEY_SPACE of="${ICC_MODULUS}.leftmost" 2>/dev/null
    
    # Extract remainder
    dd if="$ICC_MODULUS" bs=1 skip=$KEY_SPACE of="$ICC_REMAINDER" 2>/dev/null
    ICC_KEY_IN_CERT="${ICC_MODULUS}.leftmost"
else
    print_info "ICC key fits entirely in certificate (no remainder needed)"
    ICC_KEY_IN_CERT="$ICC_MODULUS"
    REMAINDER_SIZE=0
    touch "$ICC_REMAINDER"
fi

# Build ICC certificate structure
print_info "Constructing ICC certificate plaintext..."

CERT_PLAINTEXT=$(mktemp)
CERT_METADATA=$(mktemp)

# Calculate exponent length before building metadata
EXPONENT_LEN=${#ICC_EXPONENT_HEX}
EXPONENT_LEN=$(( (EXPONENT_LEN + 1) / 2 ))

# Extract PAN parts
PAN_LENGTH=${#CARD_PAN}
# For ICC cert, we typically use rightmost 10 digits of PAN (excluding check digit)
PAN_RIGHTMOST_10="${CARD_PAN:$(($PAN_LENGTH-11)):10}"

# Build metadata
{
    # Header (1 byte)
    printf '\x6A'
    
    # Certificate Format (1 byte) - 0x04 for ICC Public Key
    printf '\x04'
    
    # Application PAN - rightmost 10 digits, left justified (10 bytes)
    # BCD encoded, padded with 'F' on right if needed
    PAN_HEX=$(echo -n "$PAN_RIGHTMOST_10" | sed 's/\(.\)\(.\)/\1\2/g')
    # Pad to 10 bytes (20 hex chars)
    while [ ${#PAN_HEX} -lt 20 ]; do
        PAN_HEX="${PAN_HEX}F"
    done
    echo -n "$PAN_HEX" | xxd -r -p
    
    # Certificate Expiration Date (2 bytes) - MMYY format
    echo -n "${EXPIRY_DATE:2:2}${EXPIRY_DATE:0:2}" | xxd -r -p
    
    # Certificate Serial Number (3 bytes)
    echo -n "${CERT_SERIAL:0:6}" | xxd -r -p
    
    # Hash Algorithm Indicator (1 byte) - 0x02 for SHA-256
    printf '\x02'
    
    # ICC Public Key Algorithm (1 byte) - 0x01 for RSA
    printf '\x01'
    
    # ICC Public Key Length (1 byte) - for 256, use 0x00
    ICC_SIZE_BYTE=$(( ICC_MODULUS_SIZE % 256 ))
    printf "\\x$(printf '%02X' $ICC_SIZE_BYTE)"
    
    # ICC Public Key Exponent Length (1 byte)
    printf "\\x$(printf '%02X' $EXPONENT_LEN)"
    
} > "$CERT_METADATA"

METADATA_ACTUAL=$(stat -f%z "$CERT_METADATA" 2>/dev/null || stat -c%s "$CERT_METADATA" 2>/dev/null)

# Build full certificate
{
    cat "$CERT_METADATA"
    
    # ICC Public Key or Leftmost Digits
    cat "$ICC_KEY_IN_CERT"
    
    # Hash (SHA-256 = 32 bytes) - placeholder
    dd if=/dev/urandom bs=1 count=32 2>/dev/null
    
    # Trailer (1 byte)
    printf '\xBC'
    
} > "$CERT_PLAINTEXT"

PLAINTEXT_SIZE=$(stat -f%z "$CERT_PLAINTEXT" 2>/dev/null || stat -c%s "$CERT_PLAINTEXT" 2>/dev/null)
print_info "Certificate plaintext: $PLAINTEXT_SIZE bytes"

# Verify size
if [ $PLAINTEXT_SIZE -ne $CERT_SIZE ]; then
    print_error "Certificate plaintext size mismatch!"
    print_error "Expected: $CERT_SIZE bytes, Got: $PLAINTEXT_SIZE bytes"
    print_info "Debug: Metadata size: $METADATA_ACTUAL bytes (expected: $METADATA_SIZE bytes)"
    
    KEY_IN_CERT_SIZE=$(stat -f%z "$ICC_KEY_IN_CERT" 2>/dev/null || stat -c%s "$ICC_KEY_IN_CERT" 2>/dev/null)
    print_info "Debug: Key-in-cert size: $KEY_IN_CERT_SIZE bytes (expected: $KEY_SPACE bytes)"
    
    rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ICC_MODULUS}.leftmost"
    exit 1
fi

# Step 6: Sign certificate with Issuer private key
print_step "6/6 Signing certificate with Issuer private key..."

# RSA signature with Issuer key (raw RSA, no padding)
if openssl pkeyutl -sign -inkey "$ISSUER_PRIVATE_KEY" -in "$CERT_PLAINTEXT" -out "$ICC_CERT" -pkeyopt rsa_padding_mode:none 2>/dev/null; then
    print_info "Signed with pkeyutl (raw RSA)"
elif openssl rsautl -sign -inkey "$ISSUER_PRIVATE_KEY" -in "$CERT_PLAINTEXT" -out "$ICC_CERT" -raw 2>/dev/null; then
    print_info "Signed with rsautl (raw RSA)"
else
    print_error "Failed to sign certificate with Issuer key"
    print_info "Tried both pkeyutl and rsautl"
    rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ICC_MODULUS}.leftmost"
    exit 1
fi

if [ ! -f "$ICC_CERT" ]; then
    print_error "Certificate file was not created"
    rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ICC_MODULUS}.leftmost"
    exit 1
fi

CERT_SIZE_ACTUAL=$(stat -f%z "$ICC_CERT" 2>/dev/null || stat -c%s "$ICC_CERT" 2>/dev/null)
print_success "Certificate signed: $CERT_SIZE_ACTUAL bytes"

# Cleanup temp files
rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ICC_MODULUS}.leftmost"

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Certificate Generation Complete"
print_header "─────────────────────────────────────────────────────────"
echo ""

# Generate info file
print_info "Generating information file..."

cat > "$INFO_FILE" << EOF
Colossus Network ICC (Card) Certificate
========================================

Generated: $(date)
Card PAN: $CARD_PAN
Algorithm: RSA-$KEY_SIZE
Hash Algorithm: SHA-256

ICC Public Key Parameters:
---------------------------
Modulus Size:     $ICC_MODULUS_SIZE bytes ($(($ICC_MODULUS_SIZE * 8)) bits)
Public Exponent:  $ICC_EXPONENT_DEC (0x$ICC_EXPONENT_HEX)

Certificate Details:
--------------------
Certificate Size: $CERT_SIZE_ACTUAL bytes
Serial Number:    $CERT_SERIAL
Expiry Date:      $EXPIRY_DATE
PAN:              $CARD_PAN
PAN (in cert):    $PAN_RIGHTMOST_10
Remainder Size:   $REMAINDER_SIZE bytes

File Locations:
---------------
Private Key:      $ICC_PRIVATE_KEY
Public Key:       $ICC_PUBLIC_KEY
Modulus (binary): $ICC_MODULUS
Exponent (binary): $ICC_EXPONENT
Certificate:      $ICC_CERT
Remainder:        $ICC_REMAINDER

Signed By:
----------
Issuer Private Key: $ISSUER_PRIVATE_KEY

ICC Modulus (Hex):
$(xxd -p -c 32 "$ICC_MODULUS")

ICC Public Exponent (Hex):
$(xxd -p "$ICC_EXPONENT")

Certificate (Hex):
$(xxd -p -c 32 "$ICC_CERT")

Remainder (Hex):
$(xxd -p -c 32 "$ICC_REMAINDER")

Security Notice:
----------------
⚠️  KEEP THE ICC PRIVATE KEY SECURE ON THE CARD!
⚠️  This key must NEVER leave the secure element
⚠️  Used for signing transaction data (DDA/CDA)
⚠️  Compromise means card cloning is possible

EMV Usage:
----------
1. Load ICC private key onto card secure element
2. Store ICC certificate on card for terminal verification
3. Card uses ICC private key to sign transaction data
4. Terminal verifies with ICC public key from certificate

Certificate Chain:
------------------
CAPK → Signs Issuer Certificate
Issuer → Signs this ICC Certificate ✓
ICC (this key) → Signs transaction data (DDA/CDA)

Card Personalization:
---------------------
This key and certificate should be loaded onto the card during
personalization. The private key must be loaded into secure storage
and never extracted.

For more information, see COLOSSUS.md
EOF

print_success "Information file: $INFO_FILE"

# Generate YAML config
print_info "Generating YAML configuration..."

ICC_MODULUS_HEX=$(xxd -p "$ICC_MODULUS" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')
ICC_EXPONENT_HEX_SPACED=$(xxd -p "$ICC_EXPONENT" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')
ICC_CERT_HEX=$(xxd -p "$ICC_CERT" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')
ICC_REMAINDER_HEX=$(xxd -p "$ICC_REMAINDER" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')

cat > "$CONFIG_FILE" << EOF
# Colossus Network ICC Certificate Configuration
# Generated: $(date)
# Card PAN: $CARD_PAN
# Serial: $CERT_SERIAL

# ICC Public Key Exponent (tag 9F47)
- req: '80 01 9F 47 $(printf '%02X' ${#ICC_EXPONENT_HEX_SPACED}) $ICC_EXPONENT_HEX_SPACED'
  res: '90 00'

# ICC Public Key Certificate (tag 9F46) - Signed by Issuer
- req: '80 01 9F 46 $(printf '%02X' $CERT_SIZE_ACTUAL) $ICC_CERT_HEX'
  res: '90 00'

EOF

if [ $REMAINDER_SIZE -gt 0 ]; then
    cat >> "$CONFIG_FILE" << EOF
# ICC Public Key Remainder (tag 9F48) - $REMAINDER_SIZE bytes
- req: '80 01 9F 48 $(printf '%02X' $REMAINDER_SIZE) $ICC_REMAINDER_HEX'
  res: '90 00'

EOF
fi

cat >> "$CONFIG_FILE" << EOF
# Card PAN (tag 5A)
- req: '80 01 00 5A $(printf '%02X' ${#CARD_PAN}) $(echo -n $CARD_PAN | sed 's/../& /g')'
  res: '90 00'

# Note: The ICC certificate must be verified by terminals using the Issuer public key
# The complete certificate chain: CAPK → Issuer → ICC
# The ICC private key is used on-card to sign transaction data for CDA/DDA
EOF

print_success "YAML configuration: $CONFIG_FILE"

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  ICC Key Details"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_info "ICC Public Key:"
openssl rsa -pubin -in "$ICC_PUBLIC_KEY" -noout -text 2>/dev/null | head -20

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Security Warnings"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_warning "CRITICAL SECURITY NOTICES:"
echo ""
echo "  1. 🔒 The ICC private key is the card's identity"
echo "  2. 🔒 Load $ICC_PRIVATE_KEY onto card secure element ONLY"
echo "  3. 🔒 Private key must NEVER be extractable from card"
echo "  4. 🔒 Used for CDA/DDA signing during transactions"
echo "  5. 🔒 Compromise = card can be cloned"
echo "  6. 🔒 Delete private key file after loading to card"
echo "  7. 🔒 Each card gets a UNIQUE ICC key pair"
echo ""

print_header "─────────────────────────────────────────────────────────"
print_header "  Next Steps"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_info "Your ICC certificate is ready! Next steps:"
echo ""
echo "  1. ✓ CAPK generated"
echo "  2. ✓ Issuer key and certificate generated"
echo "  3. ✓ ICC key and certificate generated (this step)"
echo "  4. → Load ICC private key onto card secure element"
echo "  5. → Personalize card with certificates and data"
echo "  6. → DELETE ICC private key file from computer"
echo "  7. → Deploy CAPK and Issuer cert to terminals"
echo ""

print_info "Quick reference:"
echo ""
echo "  View ICC public key:"
echo "    cat $ICC_PUBLIC_KEY"
echo ""
echo "  View certificate (hex):"
echo "    xxd $ICC_CERT"
echo ""
echo "  View full details:"
echo "    cat $INFO_FILE"
echo ""
echo "  Card personalization commands:"
echo "    cat $CONFIG_FILE"
echo ""
echo "  Complete personalization:"
echo "    ./personalize-colossus-card.sh $CARD_PAN"
echo ""

print_success "✓ ICC certificate generation complete!"
echo ""
print_info "All files saved to: $OUTPUT_DIR"
print_warning "⚠️  Remember to securely delete ICC private key after loading to card!"
echo ""



