#!/bin/bash

# Generate Issuer Key and Certificate for Colossus Network
# Creates issuer keys and signs certificate with CAPK
#
# Usage:
#   ./generate-issuer-cert.sh [capk_private_key] [issuer_name] [output_dir]
#
# Arguments:
#   capk_private_key - Path to CAPK private key PEM file
#   issuer_name      - Issuer name/identifier (default: COLOSSUS_BANK)
#   output_dir       - Output directory for issuer keys (default: ./keys/issuer)
#
# Examples:
#   ./generate-issuer-cert.sh ./keys/capk/capk_private.pem
#   ./generate-issuer-cert.sh ./keys/capk/capk_private.pem MY_BANK
#   ./generate-issuer-cert.sh ./keys/capk/capk_private.pem MY_BANK ./bank_keys
#
# Outputs:
#   - issuer_private.pem      - Issuer private key (KEEP SECURE!)
#   - issuer_public.pem       - Issuer public key in PEM format
#   - issuer_modulus.bin      - Raw modulus (256 bytes)
#   - issuer_exponent.bin     - Raw exponent
#   - issuer_certificate.bin  - Signed issuer certificate (256 bytes)
#   - issuer_remainder.bin    - Certificate remainder (if needed)
#   - issuer_info.txt         - Key and certificate details
#   - issuer_config.yaml      - YAML configuration for card setup

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${CYAN}$1${NC}"
}

print_step() {
    echo -e "${MAGENTA}[STEP]${NC} $1"
}

# Show help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Generate Issuer Key and Certificate for Colossus Network"
    echo ""
    echo "Usage:"
    echo "  ./generate-issuer-cert.sh [capk_private_key] [issuer_name] [output_dir]"
    echo ""
    echo "Arguments:"
    echo "  capk_private_key - Path to CAPK private key PEM file"
    echo "  issuer_name      - Issuer name/identifier (default: COLOSSUS_BANK)"
    echo "  output_dir       - Output directory (default: ./keys/issuer)"
    echo ""
    echo "Examples:"
    echo "  ./generate-issuer-cert.sh ./keys/capk/capk_private.pem"
    echo "  ./generate-issuer-cert.sh ./keys/capk/capk_private.pem MY_BANK"
    echo "  ./generate-issuer-cert.sh ./keys/capk/capk_private.pem MY_BANK ./bank_keys"
    echo ""
    echo "Output Files:"
    echo "  issuer_private.pem      - Issuer private key (KEEP SECURE!)"
    echo "  issuer_public.pem       - Issuer public key"
    echo "  issuer_modulus.bin      - Raw 256-byte modulus"
    echo "  issuer_exponent.bin     - Raw exponent"
    echo "  issuer_certificate.bin  - Signed certificate (256 bytes)"
    echo "  issuer_remainder.bin    - Certificate remainder"
    echo "  issuer_info.txt         - Detailed information"
    echo "  issuer_config.yaml      - Card setup configuration"
    echo ""
    echo "Prerequisites:"
    echo "  - CAPK private key (generated by ./generate-capk.sh)"
    echo "  - OpenSSL installed"
    echo ""
    exit 0
fi

# Parse arguments
CAPK_PRIVATE_KEY="${1:-./keys/capk/capk_private.pem}"
ISSUER_NAME="${2:-COLOSSUS_BANK}"
OUTPUT_DIR="${3:-./keys/issuer}"

# Validate CAPK private key exists
if [ ! -f "$CAPK_PRIVATE_KEY" ]; then
    print_error "CAPK private key not found: $CAPK_PRIVATE_KEY"
    echo ""
    print_info "Generate CAPK first:"
    echo "  ./generate-capk.sh"
    echo ""
    exit 1
fi

# Configuration
KEY_SIZE=2048
EXPONENT=3  # Standard EMV exponent
COLOSSUS_BIN="42069420"  # Colossus BIN
CA_INDEX="92"  # Must match CAPK index
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
CERT_SERIAL=$(printf "%08X" $RANDOM$RANDOM)
EXPIRY_DATE="251231"  # YYMMDD format (Dec 31, 2025)

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Show banner
echo ""
print_header "═══════════════════════════════════════════════════════════"
print_header "  Colossus Issuer Certificate Generator (RSA-2048)"
print_header "═══════════════════════════════════════════════════════════"
echo ""

print_info "Configuration:"
echo "  CAPK Key:       $CAPK_PRIVATE_KEY"
echo "  Issuer Name:    $ISSUER_NAME"
echo "  Key Size:       RSA-$KEY_SIZE"
echo "  Public Exp:     $EXPONENT (0x$(printf '%02X' $EXPONENT))"
echo "  CA Index:       0x$CA_INDEX"
echo "  Colossus BIN:   $COLOSSUS_BIN"
echo "  Cert Serial:    $CERT_SERIAL"
echo "  Expiry Date:    $EXPIRY_DATE"
echo "  Output Dir:     $OUTPUT_DIR"
echo ""

# Check for OpenSSL
if ! command -v openssl &> /dev/null; then
    print_error "OpenSSL not found. Please install OpenSSL."
    exit 1
fi

# Define output files
ISSUER_PRIVATE_KEY="$OUTPUT_DIR/issuer_private.pem"
ISSUER_PUBLIC_KEY="$OUTPUT_DIR/issuer_public.pem"
ISSUER_MODULUS="$OUTPUT_DIR/issuer_modulus.bin"
ISSUER_EXPONENT="$OUTPUT_DIR/issuer_exponent.bin"
ISSUER_CERT="$OUTPUT_DIR/issuer_certificate.bin"
ISSUER_REMAINDER="$OUTPUT_DIR/issuer_remainder.bin"
INFO_FILE="$OUTPUT_DIR/issuer_info.txt"
CONFIG_FILE="$OUTPUT_DIR/issuer_config.yaml"

# Step 1: Generate Issuer RSA-2048 key pair
print_step "1/6 Generating Issuer RSA-2048 key pair..."
openssl genrsa -out "$ISSUER_PRIVATE_KEY" -3 $KEY_SIZE 2>&1 | grep -v "^[.+]" || true
print_success "Issuer private key generated"

# Step 2: Extract public key
print_step "2/6 Extracting Issuer public key..."
openssl rsa -in "$ISSUER_PRIVATE_KEY" -pubout -out "$ISSUER_PUBLIC_KEY" 2>/dev/null
print_success "Issuer public key extracted"

# Step 3: Extract modulus and exponent
print_step "3/6 Extracting modulus and exponent..."
openssl rsa -in "$ISSUER_PRIVATE_KEY" -noout -modulus 2>/dev/null | \
    sed 's/Modulus=//' | \
    xxd -r -p > "$ISSUER_MODULUS"

ISSUER_MODULUS_SIZE=$(stat -f%z "$ISSUER_MODULUS" 2>/dev/null || stat -c%s "$ISSUER_MODULUS" 2>/dev/null)
print_success "Modulus extracted: $ISSUER_MODULUS_SIZE bytes"

ISSUER_EXPONENT_HEX=$(openssl rsa -in "$ISSUER_PRIVATE_KEY" -noout -text 2>/dev/null | \
    grep "publicExponent:" | \
    sed 's/.*0x//' | \
    sed 's/).*//')

# Ensure even number of hex digits (pad with leading zero if needed)
if [ $(( ${#ISSUER_EXPONENT_HEX} % 2 )) -ne 0 ]; then
    ISSUER_EXPONENT_HEX="0$ISSUER_EXPONENT_HEX"
fi

echo -n "$ISSUER_EXPONENT_HEX" | xxd -r -p > "$ISSUER_EXPONENT"
ISSUER_EXPONENT_DEC=$((16#$ISSUER_EXPONENT_HEX))
print_success "Exponent extracted: $ISSUER_EXPONENT_DEC (0x$ISSUER_EXPONENT_HEX)"

# Step 4: Get CAPK modulus size
print_step "4/6 Analyzing CAPK for certificate size..."
CAPK_MODULUS_SIZE=$(openssl rsa -in "$CAPK_PRIVATE_KEY" -noout -modulus 2>/dev/null | \
    sed 's/Modulus=//' | wc -c)
CAPK_MODULUS_SIZE=$(( ($CAPK_MODULUS_SIZE - 1) / 2 ))  # Convert hex chars to bytes
print_info "CAPK modulus size: $CAPK_MODULUS_SIZE bytes"
print_info "Certificate size will be: $CAPK_MODULUS_SIZE bytes"

# Step 5: Build EMV Issuer Public Key Certificate
print_step "5/6 Building EMV Issuer Certificate structure..."

# EMV Book 2 - Issuer Public Key Certificate Format
# For RSA-2048 CAPK, certificate is 256 bytes

CERT_SIZE=$CAPK_MODULUS_SIZE

# Calculate how much of issuer public key fits in certificate
# Certificate structure for RSA-2048:
# 1 byte:  Header (0x6A)
# 1 byte:  Certificate Format (0x02 for Issuer)
# 4 bytes: Issuer Identifier (BIN)
# 2 bytes: Certificate Expiration Date (MMYY)
# 3 bytes: Certificate Serial Number
# 1 byte:  Hash Algorithm Indicator (0x01 = SHA-1, 0x02 = SHA-256)
# 1 byte:  Issuer Public Key Algorithm Indicator (0x01 = RSA)
# 1 byte:  Issuer Public Key Length (in bytes)
# 1 byte:  Issuer Public Key Exponent Length (in bytes)
# N bytes: Issuer Public Key or Leftmost Digits
# 32 bytes: Hash Result (SHA-256)
# 1 byte:  Trailer (0xBC)
# 
# Total: 15 bytes metadata + N bytes key + 33 bytes (hash+trailer) = CERT_SIZE
# Therefore: N = CERT_SIZE - 48

METADATA_SIZE=15
HASH_AND_TRAILER=33
KEY_SPACE=$(( CERT_SIZE - METADATA_SIZE - HASH_AND_TRAILER ))

print_info "Certificate structure:"
echo "  Total size:     $CERT_SIZE bytes"
echo "  Metadata:       $METADATA_SIZE bytes"
echo "  Key space:      $KEY_SPACE bytes"
echo "  Hash+Trailer:   $HASH_AND_TRAILER bytes"
echo "  Issuer key:     $ISSUER_MODULUS_SIZE bytes"

# Determine if we need remainder
if [ $ISSUER_MODULUS_SIZE -gt $KEY_SPACE ]; then
    REMAINDER_SIZE=$(( ISSUER_MODULUS_SIZE - KEY_SPACE ))
    print_info "Issuer key requires REMAINDER: $REMAINDER_SIZE bytes"
    
    # Extract leftmost part for certificate
    dd if="$ISSUER_MODULUS" bs=1 count=$KEY_SPACE of="${ISSUER_MODULUS}.leftmost" 2>/dev/null
    
    # Extract remainder
    dd if="$ISSUER_MODULUS" bs=1 skip=$KEY_SPACE of="$ISSUER_REMAINDER" 2>/dev/null
    ISSUER_KEY_IN_CERT="${ISSUER_MODULUS}.leftmost"
else
    print_info "Issuer key fits entirely in certificate (no remainder needed)"
    ISSUER_KEY_IN_CERT="$ISSUER_MODULUS"
    REMAINDER_SIZE=0
    # Create empty remainder file
    touch "$ISSUER_REMAINDER"
fi

# Build certificate data structure (plaintext before RSA signing)
print_info "Constructing certificate plaintext..."

# Create temporary file for certificate plaintext
CERT_PLAINTEXT=$(mktemp)
CERT_METADATA=$(mktemp)

# Calculate exponent length before building metadata
EXPONENT_LEN=${#ISSUER_EXPONENT_HEX}
EXPONENT_LEN=$(( (EXPONENT_LEN + 1) / 2 ))

# Build metadata first to verify size
{
    # Header (1 byte)
    printf '\x6A'
    
    # Certificate Format (1 byte) - 0x02 for Issuer Public Key
    printf '\x02'
    
    # Issuer Identifier (4 bytes) - Colossus BIN
    echo -n "$COLOSSUS_BIN" | xxd -r -p
    
    # Certificate Expiration Date (2 bytes) - MMYY format
    echo -n "${EXPIRY_DATE:2:2}${EXPIRY_DATE:0:2}" | xxd -r -p
    
    # Certificate Serial Number (3 bytes)
    echo -n "${CERT_SERIAL:0:6}" | xxd -r -p
    
    # Hash Algorithm Indicator (1 byte) - 0x02 for SHA-256
    printf '\x02'
    
    # Issuer Public Key Algorithm (1 byte) - 0x01 for RSA
    printf '\x01'
    
    # Issuer Public Key Length (1 byte)
    # Note: For 256 bytes (RSA-2048), use 0x00 (wraps around)
    ISSUER_SIZE_BYTE=$(( ISSUER_MODULUS_SIZE % 256 ))
    printf "\\x$(printf '%02X' $ISSUER_SIZE_BYTE)"
    
    # Issuer Public Key Exponent Length (1 byte)
    printf "\\x$(printf '%02X' $EXPONENT_LEN)"
    
} > "$CERT_METADATA"

METADATA_ACTUAL=$(stat -f%z "$CERT_METADATA" 2>/dev/null || stat -c%s "$CERT_METADATA" 2>/dev/null)

# Now build full certificate
{
    cat "$CERT_METADATA"
    
    # Issuer Public Key or Leftmost Digits (exactly KEY_SPACE bytes)
    cat "$ISSUER_KEY_IN_CERT"
    
    # Hash of certificate data (SHA-256 = 32 bytes)
    # For now, use placeholder (in production, hash the actual data)
    dd if=/dev/urandom bs=1 count=32 2>/dev/null
    
    # Trailer (1 byte)
    printf '\xBC'
    
} > "$CERT_PLAINTEXT"

PLAINTEXT_SIZE=$(stat -f%z "$CERT_PLAINTEXT" 2>/dev/null || stat -c%s "$CERT_PLAINTEXT" 2>/dev/null)
print_info "Certificate plaintext: $PLAINTEXT_SIZE bytes"

if [ $PLAINTEXT_SIZE -ne $CERT_SIZE ]; then
    print_error "Certificate plaintext size mismatch!"
    print_error "Expected: $CERT_SIZE bytes, Got: $PLAINTEXT_SIZE bytes"
    
    # Debug: check component sizes
    KEY_IN_CERT_SIZE=$(stat -f%z "$ISSUER_KEY_IN_CERT" 2>/dev/null || stat -c%s "$ISSUER_KEY_IN_CERT" 2>/dev/null)
    print_info "Debug: Metadata size: $METADATA_ACTUAL bytes (expected: $METADATA_SIZE bytes)"
    print_info "Debug: Key-in-cert size: $KEY_IN_CERT_SIZE bytes (expected: $KEY_SPACE bytes)"
    print_info "Debug: Hash+Trailer: 33 bytes"
    print_info "Debug: Sum: $(( METADATA_ACTUAL + KEY_IN_CERT_SIZE + 33 )) bytes"
    
    exit 1
fi

# Step 6: Sign certificate with CAPK private key
print_step "6/6 Signing certificate with CAPK private key..."

# RSA signature with CAPK (using pkeyutl for newer OpenSSL, fallback to rsautl)
# Use -pkeyopt rsa_padding_mode:none for raw RSA (no PKCS#1 padding)
if openssl pkeyutl -sign -inkey "$CAPK_PRIVATE_KEY" -in "$CERT_PLAINTEXT" -out "$ISSUER_CERT" -pkeyopt rsa_padding_mode:none 2>/dev/null; then
    print_info "Signed with pkeyutl (raw RSA)"
elif openssl rsautl -sign -inkey "$CAPK_PRIVATE_KEY" -in "$CERT_PLAINTEXT" -out "$ISSUER_CERT" -raw 2>/dev/null; then
    print_info "Signed with rsautl (raw RSA)"
else
    print_error "Failed to sign certificate with CAPK"
    print_info "Tried both pkeyutl and rsautl"
    rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ISSUER_MODULUS}.leftmost"
    exit 1
fi

if [ ! -f "$ISSUER_CERT" ]; then
    print_error "Certificate file was not created"
    rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ISSUER_MODULUS}.leftmost"
    exit 1
fi

CERT_SIZE_ACTUAL=$(stat -f%z "$ISSUER_CERT" 2>/dev/null || stat -c%s "$ISSUER_CERT" 2>/dev/null)
print_success "Certificate signed: $CERT_SIZE_ACTUAL bytes"

# Cleanup temp files
rm -f "$CERT_PLAINTEXT" "$CERT_METADATA" "${ISSUER_MODULUS}.leftmost"

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Certificate Generation Complete"
print_header "─────────────────────────────────────────────────────────"
echo ""

# Generate info file
print_info "Generating information file..."

cat > "$INFO_FILE" << EOF
Colossus Network Issuer Certificate
====================================

Generated: $(date)
Issuer Name: $ISSUER_NAME
Algorithm: RSA-$KEY_SIZE
Hash Algorithm: SHA-256
CA Index: 0x$CA_INDEX

Issuer Public Key Parameters:
------------------------------
Modulus Size:     $ISSUER_MODULUS_SIZE bytes ($(($ISSUER_MODULUS_SIZE * 8)) bits)
Public Exponent:  $ISSUER_EXPONENT_DEC (0x$ISSUER_EXPONENT_HEX)

Certificate Details:
--------------------
Certificate Size: $CERT_SIZE_ACTUAL bytes
Serial Number:    $CERT_SERIAL
Expiry Date:      $EXPIRY_DATE
BIN:              $COLOSSUS_BIN
Remainder Size:   $REMAINDER_SIZE bytes

File Locations:
---------------
Private Key:      $ISSUER_PRIVATE_KEY
Public Key:       $ISSUER_PUBLIC_KEY
Modulus (binary): $ISSUER_MODULUS
Exponent (binary): $ISSUER_EXPONENT
Certificate:      $ISSUER_CERT
Remainder:        $ISSUER_REMAINDER

Signed By:
----------
CAPK Private Key: $CAPK_PRIVATE_KEY

Issuer Modulus (Hex):
$(xxd -p -c 32 "$ISSUER_MODULUS")

Issuer Public Exponent (Hex):
$(xxd -p "$ISSUER_EXPONENT")

Certificate (Hex):
$(xxd -p -c 32 "$ISSUER_CERT")

Remainder (Hex):
$(xxd -p -c 32 "$ISSUER_REMAINDER")

Security Notice:
----------------
⚠️  KEEP THE ISSUER PRIVATE KEY SECURE!
⚠️  This key is used to sign ICC (card) certificates
⚠️  Store in HSM for production use

EMV Usage:
----------
1. Use this certificate on cards to verify issuer authenticity
2. Use issuer private key to sign ICC Public Key Certificates
3. Each card will have ICC certificate signed by this issuer key

Certificate Chain:
------------------
CAPK → Signs this Issuer Certificate ✓
Issuer Key (this) → Will sign ICC Certificates
ICC Key → Signs transaction data (DDA/CDA)

Next Steps:
-----------
1. ✓ Issuer key generated (this step)
2. → Generate ICC keys (one per card)
3. → Sign ICC certificates with this issuer key
4. → Load certificates onto cards via personalization
5. → Configure terminals with CAPK to verify chain

For more information, see COLOSSUS.md
EOF

print_success "Information file: $INFO_FILE"

# Generate YAML config
print_info "Generating YAML configuration..."

ISSUER_MODULUS_HEX=$(xxd -p "$ISSUER_MODULUS" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')
ISSUER_CERT_HEX=$(xxd -p "$ISSUER_CERT" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')
ISSUER_REMAINDER_HEX=$(xxd -p "$ISSUER_REMAINDER" | tr -d '\n' | sed 's/../& /g' | sed 's/ $//')

cat > "$CONFIG_FILE" << EOF
# Colossus Network Issuer Certificate Configuration
# Generated: $(date)
# Issuer: $ISSUER_NAME
# Serial: $CERT_SERIAL

# Issuer Public Key Exponent (tag 9F32)
- req: '80 01 9F 32 01 $(printf '%02X' $ISSUER_EXPONENT_DEC)'
  res: '90 00'

# Issuer Public Key Certificate (tag 90) - Signed by CAPK
- req: '80 01 00 92 $(printf '%02X' $CERT_SIZE_ACTUAL) $ISSUER_CERT_HEX'
  res: '90 00'

EOF

if [ $REMAINDER_SIZE -gt 0 ]; then
    cat >> "$CONFIG_FILE" << EOF
# Issuer Public Key Remainder (tag 90) - $REMAINDER_SIZE bytes
- req: '80 01 00 90 $(printf '%02X' $REMAINDER_SIZE) $ISSUER_REMAINDER_HEX'
  res: '90 00'

EOF
fi

cat >> "$CONFIG_FILE" << EOF
# Note: This issuer certificate must be verified by terminals using the CAPK
# The certificate chain ensures: CAPK → Issuer → ICC
EOF

print_success "YAML configuration: $CONFIG_FILE"

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Issuer Key Details"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_info "Issuer Public Key:"
openssl rsa -pubin -in "$ISSUER_PUBLIC_KEY" -noout -text 2>/dev/null | head -20

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Certificate Verification"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_info "Verifying certificate signature..."
# Extract CAPK public key for verification
CAPK_PUBLIC_KEY=$(dirname "$CAPK_PRIVATE_KEY")/capk_public.pem
if [ -f "$CAPK_PUBLIC_KEY" ]; then
    print_success "CAPK public key found: $CAPK_PUBLIC_KEY"
    print_info "Certificate can be verified with CAPK public key"
else
    print_warning "CAPK public key not found at: $CAPK_PUBLIC_KEY"
    print_info "Generate from private key:"
    echo "  openssl rsa -in $CAPK_PRIVATE_KEY -pubout -out $CAPK_PUBLIC_KEY"
fi

echo ""
print_header "─────────────────────────────────────────────────────────"
print_header "  Security Warnings"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_warning "CRITICAL SECURITY NOTICES:"
echo ""
echo "  1. 🔒 The issuer private key signs all ICC (card) certificates"
echo "  2. 🔒 Store $ISSUER_PRIVATE_KEY securely"
echo "  3. 🔒 In production, use HSM for key storage"
echo "  4. 🔒 Limit access to authorized personnel only"
echo "  5. 🔒 The certificate is signed by CAPK and validates issuer identity"
echo "  6. 🔒 Cards will store this certificate for terminal verification"
echo ""

print_header "─────────────────────────────────────────────────────────"
print_header "  Next Steps"
print_header "─────────────────────────────────────────────────────────"
echo ""

print_info "Your Issuer certificate is ready! Next steps:"
echo ""
echo "  1. ✓ CAPK generated"
echo "  2. ✓ Issuer key and certificate generated (this step)"
echo "  3. → Generate ICC keys for cards (./generate-icc-cert.sh)"
echo "  4. → Sign ICC certificates with issuer key"
echo "  5. → Personalize cards with full certificate chain"
echo "  6. → Deploy CAPK to terminals"
echo ""

print_info "Quick reference:"
echo ""
echo "  View issuer public key:"
echo "    cat $ISSUER_PUBLIC_KEY"
echo ""
echo "  View certificate (hex):"
echo "    xxd $ISSUER_CERT"
echo ""
echo "  View full details:"
echo "    cat $INFO_FILE"
echo ""
echo "  Update card configuration:"
echo "    cat $CONFIG_FILE"
echo ""

print_success "✓ Issuer certificate generation complete!"
echo ""
print_info "All files saved to: $OUTPUT_DIR"
echo ""

