package emvcardsimulator;

/**
 * Build configuration constants — generated by Gradle.
 * Build type: dev
 *
 * When PRODUCTION is true, admin/personalization commands (80xx) are stripped
 * from the applet. The card can only be personalized via GP STORE DATA.
 */
public class BuildConfig {
    public static final boolean PRODUCTION = false;
}
